# Generated by Django 3.0.8 on 2020-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(help_text='Nome do colaborador', max_length=100),
        ),
    ]
