# Generated by Django 3.0.8 on 2020-07-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colaboradores', '0003_auto_20200730_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
