# Generated by Django 3.1.4 on 2021-01-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_auto_20200804_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='imagem',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
